#=================
# Makefile Codage
#=================

#-------------
# Executables 
#-------------

agent : agent.c 
	gcc -pthread -Wall -g agent.c -o test

#----------------------------
# Gestion generale du projet
#----------------------------

all : agent

clean :
	rm *.o
	rm test

